In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

In [ ]:
def text_to_num(df: pd.DataFrame, col):
    le=LabelEncoder()
    df[col] = le.fit_transform(df[col])


def scale_num(df, col):
    sc= StandardScaler()
    df[col] = sc.fit_transform(df[[col]])


def typesof(df, col):
    print("The Count of Unique Values:" , df[col].nunique())
    print("----------------------------------------------------------------------------------------------------------------")
    print("The Unique Values is:" , df[col].unique())
    print("----------------------------------------------------------------------------------------------------------------")
    print("Count of Unique Values:" , df[col].value_counts())


def isnn(df, col):
    if df[col].isna().sum() > 0:
        return True
    else:
        return False


def fillnn(df, col):
    m = df[col].mode().iloc[0]
    # print(m)
    df[col]=df[col].fillna(m)

In [ ]:
df = pd.read_csv('/content/loan_approval_dataset.csv')

In [ ]:
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [ ]:
df[' education'].value_counts()

 education
 Graduate        2144
 Not Graduate    2125
Name: count, dtype: int64

In [ ]:
df.drop('loan_id',inplace=True, axis=1)

In [ ]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.isna().sum()

 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0    no_of_dependents          4269 non-null   int64
 1    education                 4269 non-null   object
 2    self_employed             4269 non-null   object
 3    income_annum              4269 non-null   int64
 4    loan_amount               4269 non-null   int64
 5    loan_term                 4269 non-null   int64
 6    cibil_score               4269 non-null   int64
 7    residential_assets_value  4269 non-null   int64
 8    commercial_assets_value   4269 non-null   int64
 9    luxury_assets_value       4269 non-null   int64
 10   bank_asset_value          4269 non-null   int64
 11   loan_status               4269 non-null   object
dtypes: int64(9), object(3)
memory usage: 400.3+ KB

In [ ]:
df.columns

Index([' no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [ ]:
text_to_num(df, ' education')

In [ ]:
text_to_num(df, ' self_employed')

In [ ]:
cal = df.columns[df.dtypes == 'int']

In [ ]:
cal

Index([' no_of_dependents', ' income_annum', ' loan_amount', ' loan_term',
       ' cibil_score', ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value'],
      dtype='object')

In [ ]:
cal = cal.delete([1])

In [ ]:
for col in cal:
    scale_num(df, col)

In [ ]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,-0.294102,0,0,1.617979,1.633052,0.192617,1.032792,-0.780058,2.877289,0.832028,0.930304,Approved
1,-1.473548,1,1,-0.341750,-0.324414,-0.508091,-1.061051,-0.733924,-0.631921,-0.694993,-0.515936,Rejected
2,0.295621,0,0,1.439822,1.610933,1.594031,-0.544840,-0.057300,-0.107818,1.996520,2.407316,Rejected
3,0.295621,0,0,1.119139,1.721525,-0.508091,-0.771045,1.649637,-0.381263,0.897943,0.899533,Rejected
4,1.475067,1,1,1.689242,1.002681,1.594031,-1.264055,0.757724,0.735304,1.568075,0.007172,Rejected

In [ ]:
text_to_num(df, ' loan_status')

In [ ]:
typesof(df, ' loan_status')

The Count of Unique Values: 2
----------------------------------------------------------------------------------------------------------------
The Unique Values is: [0 1]
----------------------------------------------------------------------------------------------------------------
Count of Unique Values:  loan_status
0    2656
1    1613
Name: count, dtype: int64

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(' loan_status', axis=1), df[' loan_status'], test_size=0.2, random_state=42)

In [ ]:
model = Sequential()
model.add(Dense(128, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train,epochs=15)

Epoch 1/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8397 - loss: 0.4029
Epoch 2/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9309 - loss: 0.1664
Epoch 3/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9391 - loss: 0.1430
Epoch 4/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9495 - loss: 0.1249
Epoch 5/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9528 - loss: 0.1191
Epoch 6/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9637 - loss: 0.0948
Epoch 7/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9638 - loss: 0.0878
Epoch 8/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9707 - loss: 0.0888
Epoch 9/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9683 - loss: 0.0778
Epoch 10/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9779 - loss: 0.0690
Epoch 11/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9774 - loss: 0.0690
Epoch 12/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9797 - loss: 0.0511
Epoch 13/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9739 - loss: 0.0716
Epoch 14/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9811 - loss: 0.0524
Epoch 15/15
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9808 - loss: 0.0491

In [ ]:
model.evaluate(x_test,y_test)

27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9480 - loss: 0.1009

[0.11013548821210861, 0.9484777450561523]

In [ ]:
pred = model.predict(x_test)

27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [ ]:
for i in range(len(pred)):
  if pred[i] >= 0.5:
    pred[i] = 1
  else:
    pred[i] = 0

In [ ]:
for i in range(len(pred)):
  print(pred[i], y_test.iloc[i])

[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 0
[0.] 0
[0.] 1
[0.] 0
[0.] 1
[1.] 1
[1.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 1
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 1
[0.] 0
[0.] 0
[0.] 1
[1.] 1
[1.] 1
[1.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 0
[1.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 1
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[1.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[1.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[1.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 0
[0.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 1
[0.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[0.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 0
[0.] 1
[1.] 1
[1.] 1
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 1
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 1
[1.] 1
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[0.] 0
[1.] 1
[0.] 0
[1.] 1
[0.] 0
[1.] 0
[0.] 0
[1.] 1
[1.] 1

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       536
           1       0.93      0.94      0.93       318

    accuracy                           0.95       854
   macro avg       0.94      0.95      0.95       854
weighted avg       0.95      0.95      0.95       854

In [ ]:
model.save('loan_k.keras')

In [ ]:
from keras.models import load_model

In [ ]:
m = load_model('loan_k.keras')

In [ ]:
m.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])